@startuml
'FileSelected -up FileSelected : <b>pbSelect</b> clicked(bool)
'NoFileSelected -down NoFileSelected : pbSelect clicked(bool)
[*] -down-> SelectFile
SelectFile -down-> PathSelected : <b>tePath</b>  changed()
Error -down-> PathSelected : <b>tePath</b>  changed()
PathSelected -right-> Compare : <b>pbStart</b> clicked()
'Open -right-> Compare : <b>this</b> opened()
Compare -down-> Error : <b>this</b> error()
Compare -left-> PathSelected : <b>pbStart</b>  clicked()
Compare -right-> ViewResult : <b>this</b>  done()
ViewResult -left-> PathSelected : <b>tePath</b>  changed() \n OR \n <b>horizontalSlider</b>  changed() \n OR \n <b>cbAlgo</b>  changed()
SelectFile: <b>pbStart</b>  enabled  <b> false</b>
SelectFile: <b>pbSelect</b>  enabled  <b> true</b>
SelectFile: <b>tePath</b>  placeholderText  <b> "No directory selected..."</b>
PathSelected: <b>pbStart</b>  enabled  <b> true</b>
PathSelected: <b>pbStart</b>  placeholderText  <b> "START"</b>
PathSelected: <b>pbSelect</b>  enabled  <b> true</b>
PathSelected: <b>tePath</b>  placeholderText  <b> "/path/to/directory"</b>
PathSelected: <b>state</b>  entered() ->    <b>this</b>  clear()
Compare: <b>pbStart</b>  placeholderText  <b> "CANCEL"</b>
Compare: <b>pbSelect</b>  enabled  <b> false</b>
Compare: <b>state</b>  entered() ->    <b>this</b>  open()
Error: <b>pbStart</b>  enabled  <b> false</b>
Error: <b>pbSelect</b>  enabled  <b> true</b>
'Error: <b>tePath</b>  placeholderText  <b> "Wrong path or permissions!"</b>
'Compare: <b>pbStart</b>  enabled  <b> true</b>
ViewResult: <b>pbStart</b>  enabled  <b> false</b>
note bottom of ViewResult
    - open results in new window "Most similar files"
end note
note bottom of Compare
    - state exists only due to existence of large files,
      which might take long time to process
    - we need to find something to test that state
end note
'Result: <b>pbStart</b>  placeholderText  <b> "START"</b>
@enduml
